# Generated by Django 5.0.14 on 2026-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_service_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category for grouping, e.g. "Hair", "Skin", "Consultation".', max_length=100),
        ),
    ]
