# Generated by Django 5.0.14 on 2026-01-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for quick segmentation (e.g. VIP, Hair, Laser).', max_length=255),
        ),
    ]
